### ISSUE TITLE
creating other profiles than `app-dev` 

### ISSUE THREAD

**Issue by yahavb** [weaveworks/eks-quickstart-app-dev#33]
when `eksctl enable profile` uses `app-dev` profile, it points to `git@github.com:weaveworks/eks-quickstart-app-dev.git`. I created `git@github.com:yahavb/game-server-gitops-profile.git` and was able to `eksctl enable profile`  with this repo. What is magic behind the `app-dev` pointer? How can I add my template to be `game-server-dev`?

**Comment by codecrane** [comment]
@yahavb I am using https instead of ssh for git, but I am using a custom repo for my profile.

Example:
```
EKSCTL_EXPERIMENTAL=true eksctl \
        enable profile \
        --git-url git@github.com:myorg/myrepo \
        --git-email foo.bar@mydomain.com \
        --cluster temp-test \
        --name https://github.com/yahavb/game-server-gitops-profile.git
```

I would imagine you could just swap that over to the ssh version:
```
EKSCTL_EXPERIMENTAL=true eksctl \
        enable profile \
        --git-url git@github.com:myorg/myrepo \
        --git-email foo.bar@mydomain.com \
        --cluster temp-test \
        --name git@github.com:yahavb/game-server-gitops-profile.git
```

Hope that helps

**Comment by martina-if** [comment]
Hi @yahavb , the magic is that that name is hardcoded into eksctl because it is considered a special quickstart profile. 

Unfortunately we are not planning to hardcode user's profiles in eksctl, this is just a shortcut for specific profiles built by weaveworks for now. 

For more information you can check [the docs](https://eksctl.io/usage/gitops/#creating-your-own-quick-start-profile)
